---
title: Untitled
subtitle: "An optional subtitle"
format:
  osc-slides-revealjs: default
  #osc-slides-pptx: default
author:
  - name: Your Name
    affiliation:
      - name: Your first affiliation
        department: Your department
        city: Your city
        country: Your country
        url: https://your-affiliation-website.com
        ror: 029e6qe04 # this is the LMU Open Science Center ROR ID https://ror.org/029e6qe04
      - name: optional additional affiliations
        department: Optional department
        city: Optional city
        country: Optional country
        url: https://optional-affiliation-website.com
        ror: 000000000 # optional additional affiliation ROR ID
    orcid: 0000-0000-0000-0000
    corresponding: true
    email: your_email@domain.com
    degrees:
      - PhD
    roles: "Either a CRediT role or free text: https://quarto.org/docs/authoring/front-matter.html#roles"
  - name: second author
    orcid: 0000-0000-0000-0000
    email: your_email@domain.com
date: last-modified
license: "CC BY-SA" # default license for OSC content
funding: "A statement about funding. If referencing a specific grant, see this section: https://quarto.org/docs/authoring/front-matter.html#funding"
abstract: |
  A brief summary of your presentation. This will be displayed on the title slide and in the speaker notes.
---

## Introduction

*TODO* Create an example file that demonstrates the formatting and features of your format.


## Code Folding

The code-fold param is set to true by default for code chunks in this template. You can change this behavior by setting code-fold: false in the front matter or in individual code chunks.
```{r}
# example code chunk

1+1 # <1>
mtcars %>% # <2>
  head(1) # <2>
```


1. Talk about addition in line 3
2. Talk about the mtcars dataset in lines 4-5

Note how the bullet points correspond to the code chunk lines with the `# <1>` and `# <2>` comments. 

## New Slide

### A non-slide header

Here's some content below this header. This content will be displayed on the same slide as the "Introduction" header above, because it is not separated by a slide separator (--- or ##). You can use this feature to create sections within a slide.

---

This slide has no title. The h2 separator below creates the next slide.

## More Information

You can learn more about controlling the appearance of RevealJS output here: <https://quarto.org/docs/presentations/revealjs/>

## Appendix {.appendix}

## References

::: {#refs}
:::

